<?php

namespace ApiBundle\DocumentRepository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ContactInfoRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ContactInfoRepository extends DocumentRepository
{
}
