<?php

namespace ApiBundle\DocumentRepository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends DocumentRepository
{
    public function count()
    {
        $count = $this->createQueryBuilder()
            ->count()->getQuery()->execute();
        return $count;
    }

    public function getAllForms()
    {
        $contactInfos = $this->getDocumentManager()->getRepository('ApiBundle:ContactInfo')->findAll();

        foreach ($contactInfos as $contactInfo) {
            $id = $contactInfo->getId();
            $contactInfo->{$id} = $this->findBy(array('contactInfoId' => $id));

        }

        return $contactInfos;
    }
}
