default:
    suites:
        default:
            autoload:
                '': %paths.base%/src
            type: symfony_bundle
            bundle: ApiBundle
            contexts:
#                - ApiBundle\Features\Context\FeatureContext
                - behatch:json
                - behatch:rest
                - behatch:xml
                - behatch:browser
    extensions:
        Behat\Symfony2Extension:
            kernel:
              env: "dev"
              debug: "false"
        Behat\MinkExtension:
            sessions:
                default:
                    symfony2: ~
        Behat\WebApiExtension: ~
        Sanpi\Behatch\Extension: ~