<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ContactInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactInfoRepository extends EntityRepository
{

}
