<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Query;


/**
 * ContactInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactInfoRepository extends EntityRepository
{
    public function getInfoByEmail($email)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
        SELECT c
        FROM ApiBundle:ContactInfo c
        WHERE c.email = :email
        ')->setParameter('email', $email);
        $query->setHint(Query::HINT_INCLUDE_META_COLUMNS, true);

        return $query->getResult(Query::HYDRATE_ARRAY);
    }
}
