<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{


    public function getAllMessages()
    {

        return $this->findAll();
    }

    public function getAllForms()
    {
        $contactInfos = $this->getEntityManager()->getRepository('ApiBundle:ContactInfo')->findAll();

        foreach ($contactInfos as $contactInfo) {
            $id = $contactInfo->getId();
            $contactInfo->{$id} = $this->findBy(array('contactInfoId' => $id));
        }

        return $contactInfos;
    }

    public function getMessageById($id)
    {
        return $message = $this->find($id);
    }

    public function getFormByMessageId($id)
    {

        $messageObj = $this->find($id);
        $id = $messageObj->getId();
        $contactInfoObj = $this->getEntityManager()->getRepository('ApiBundle:ContactInfo')->find($id);

        return $contactInfoObj;
    }

    public function exists($id)
    {
        return null !== $this->find($id);
    }


}
